// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIejr1QNM5WPD0K8ezkHBDobu8fJ5L1I',
    appId: '1:508825816153:web:25bf68cc1858e8a63df548',
    messagingSenderId: '508825816153',
    projectId: 'flutterfirebase-d11e2',
    authDomain: 'flutterfirebase-d11e2.firebaseapp.com',
    storageBucket: 'flutterfirebase-d11e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC57n1mu6WJKBMWFJfFJcPMRrhnEOp10Co',
    appId: '1:508825816153:android:e6e63fa87c7462e43df548',
    messagingSenderId: '508825816153',
    projectId: 'flutterfirebase-d11e2',
    storageBucket: 'flutterfirebase-d11e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzAHRamPyGumXzZuOEd1Mbwf2w3aAURC4',
    appId: '1:508825816153:ios:b8978efa7000480d3df548',
    messagingSenderId: '508825816153',
    projectId: 'flutterfirebase-d11e2',
    storageBucket: 'flutterfirebase-d11e2.firebasestorage.app',
    iosBundleId: 'com.example.firebasetotalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzAHRamPyGumXzZuOEd1Mbwf2w3aAURC4',
    appId: '1:508825816153:ios:b8978efa7000480d3df548',
    messagingSenderId: '508825816153',
    projectId: 'flutterfirebase-d11e2',
    storageBucket: 'flutterfirebase-d11e2.firebasestorage.app',
    iosBundleId: 'com.example.firebasetotalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEjUruVJD90wYkVUWw54GJJae1V2uqBW8',
    appId: '1:508825816153:web:e5e9eaf5a859d2503df548',
    messagingSenderId: '508825816153',
    projectId: 'flutterfirebase-d11e2',
    authDomain: 'flutterfirebase-d11e2.firebaseapp.com',
    storageBucket: 'flutterfirebase-d11e2.firebasestorage.app',
  );
}
